name: Docker MultiArch

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        version:
          - 'stable'
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: false
          tags: luckyraul/aptly:${{ matrix.version }} .

      - name: Push image
        run: |
          export IMAGE_NAME=luckyraul/aptly:${{ matrix.version }}
          export IMAGE_ID=ghcr.io/luckyraul/aptly:${{ matrix.version }}

          # Change all uppercase to lowercase
          export IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          docker tag $IMAGE_NAME $IMAGE_ID
          docker push $IMAGE_ID
